### ISSUE TITLE
Create User Interface

### ISSUE THREAD

**Issue by Popesites** [Popesites/kilometersMilesConversion#1]

**Comment by Popesites** [comment]
I don't know how to create a user interface for this program, and I could use some help with that.

**Comment by KangboLu** [comment]
What kind of user interface are you looking for? You can simply write a web version. However, Google instant has already covered that.

**Comment by Popesites** [comment]
Web version would be done via JavaScript, correct? 

I want to do something similar to this: http://www.pidgeycalc.com

**Comment by Popesites** [comment]
Or similar to this : http://www.rapidtables.com/convert/length/km-to-mile.htm 👍

**Comment by KangboLu** [comment]
Maybe, You can start by design how will your the UI of convert be like. And
then, you can implement functionality to do calculation and display the
results.

**Comment by Popesites** [comment]
Started the UI Creation with an HTML Skeleton

**Comment by KangboLu** [comment]
**Go to the repository and click setting**, you can host your project under your github domain for free. Then, you can see your site easily after each commit. 
**Step 1:**
![qq 20160922192637](https://cloud.githubusercontent.com/assets/17485959/18772268/5f3261c2-80fa-11e6-9538-cd8dd546f9d0.png)
**Step 2:**
![qq 20160922165918](https://cloud.githubusercontent.com/assets/17485959/18769875/ca7a7cf4-80e5-11e6-81bc-364246519f19.png)

**Comment by jondiparra** [comment]
Can I redesign the UX to be more minimalist and clean? The template looks like generic boilerplate code -- I'd like to give it a makeover. However, this would include removing the ads and download option and we'd instead add a 'fork me on GitHub' ribbon near the top. Okay to do?

**Comment by Popesites** [comment]
@jondiparra A UX update is a good idea, however if you look at the Project storyboard you'll notice the UI Enhancements should be implemented last.

As far as removing the Ads, I think that defeats the intent around the website. I'd like to monetize this website through advertisements. If you'd like to temporarily remove ads to maximize UX enhancements that's fine. 

As far as removing the downloads option, you have a complete green light on that! 

Thanks for the comment 💯 

![screen shot 2016-09-23 at 10 32 31 pm](https://cloud.githubusercontent.com/assets/17707366/18806309/cc074ef0-81dd-11e6-94fc-c13f4ee1131c.png)

**Comment by jondiparra** [comment]
Okay, I'll work on the functionality first and then push the commits so you can see what I did. What are you working on, so I know not to mess with it?

**Comment by Popesites** [comment]
@jondiparra If you're going to work on the JavaScript functionality and the UX design afterwords I can focus on gaining backlinks and trying to improve the Web app's SEO, integrate Google Analytics, and connect the Website to a spare domain name I have (if necessary).

The spare domain name I would connect it to would most likely be desigr.com which I'm not sure if it's a good idea to change to that, let me know what you think.

**Comment by jondiparra** [comment]
@Popesites sounds good!!

**Comment by Popesites** [comment]
@jondiparra Awesome man, BTW check the newest issue, I'd like your input!
