### ISSUE TITLE
Message to Collaborators: What would you like at the copyrights below?

### ISSUE THREAD

**Issue by Popesites** [Popesites/kilometersMilesConversion#10]
Hi team,

If you notice at the bottom of the Web Application, you'll see the copyright is only for Popesites & Conner Pope. 

If you'd like to have a different Copyright at the bottom, as you all have contributed to this project & deserve to have credit, please comment below! I definitely don't want to take all credits from this project when I was not the only one working on it.

Thanks for all of your work team,

Conner R. Pope 🎱

**Comment by jondiparra** [comment]
Yeah I'm down -- I'll just add my GitHub link.
